---
engines:
 rubocop:
   enabled: true
   exclude_paths:
     - config/engines.yml
 duplication:
   enabled: true
   exclude_paths:
     - config/engines.yml
 metrics:
   enabled: true
   exclude_paths:
     - config/engines.yml
 coverage:
   enabled: true
   exclude_paths:
     - config/engines.yml
exclude_paths:
  - .bundle/
  - spec/**/*
  - lib/**/*_spec.rb
  - examples/**/*
  - fixtures/**/*
  - tmp/**/*

