engines:
  rubocop:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
ratings:
  paths:
  - "lib/**"
  - "**.rb"
exclude_paths:
- "delfos.gemspec"
- "spec/**/*.rb"
- "**/*_spec.rb"
- "fixtures/**/*"
- "**/vendor/**/*"

