language: ruby
rvm:
  - 2.3.3
before_install: gem install bundler -v 1.11.2
cache: bundler
script:
  - NEO4J_HOST=http://localhost NEO4J_PORT=7474 bundle exec rake
jdk:
  - oraclejdk7
before_install:
  # install Neo4j locally:
  - wget dist.neo4j.org/neo4j-community-2.2.0-unix.tar.gz
  - tar -xzf neo4j-community-2.2.0-unix.tar.gz
  - sed -i.bak s/dbms.security.auth_enabled=true/dbms.security.auth_enabled=false/g neo4j-community-2.2.0/conf/neo4j-server.properties
  - neo4j-community-2.2.0/bin/neo4j start

